"""add_split_bonus_transaction_types

Revision ID: 6ee20cbfbb58
Revises: 33249e032ef1
Create Date: 2025-08-15 15:59:26.370140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee20cbfbb58'
down_revision: Union[str, Sequence[str], None] = '33249e032ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'yield_amount')
    op.drop_column('transactions', 'yield_payment_date')
    op.drop_column('transactions', 'yield_amount_type')
    op.drop_column('transactions', 'yield_type')
    op.drop_column('transactions', 'yield_frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('yield_frequency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('yield_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('yield_amount_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('yield_payment_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('yield_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
