"""update_enums_to_uppercase

Revision ID: edc7ea1555ee
Revises: b121317f37d6
Create Date: 2025-08-14 03:06:44.201664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edc7ea1555ee'
down_revision: Union[str, Sequence[str], None] = 'b121317f37d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_simple_email'), table_name='users_simple')
    op.drop_index(op.f('ix_users_simple_id'), table_name='users_simple')
    op.drop_index(op.f('ix_users_simple_username'), table_name='users_simple')
    op.drop_table('users_simple')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_simple',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_simple_pkey'))
    )
    op.create_index(op.f('ix_users_simple_username'), 'users_simple', ['username'], unique=True)
    op.create_index(op.f('ix_users_simple_id'), 'users_simple', ['id'], unique=False)
    op.create_index(op.f('ix_users_simple_email'), 'users_simple', ['email'], unique=True)
    # ### end Alembic commands ###
