"""add_cupom_valor_mercado_to_transactions

Revision ID: f7df96c3c0da
Revises: edc7ea1555ee
Create Date: 2025-08-14 14:21:26.611617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7df96c3c0da'
down_revision: Union[str, Sequence[str], None] = 'edc7ea1555ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_simple_email'), table_name='users_simple')
    op.drop_index(op.f('ix_users_simple_id'), table_name='users_simple')
    op.drop_index(op.f('ix_users_simple_username'), table_name='users_simple')
    op.drop_table('users_simple')
    op.add_column('transactions', sa.Column('cupom', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('valor_mercado', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'valor_mercado')
    op.drop_column('transactions', 'cupom')
    op.create_table('users_simple',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_simple_pkey'))
    )
    op.create_index(op.f('ix_users_simple_username'), 'users_simple', ['username'], unique=True)
    op.create_index(op.f('ix_users_simple_id'), 'users_simple', ['id'], unique=False)
    op.create_index(op.f('ix_users_simple_email'), 'users_simple', ['email'], unique=True)
    # ### end Alembic commands ###
