"""add_yield_columns_to_transactions

Revision ID: feae072ae4c4
Revises: f7df96c3c0da
Create Date: 2025-08-14 15:42:37.943548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feae072ae4c4'
down_revision: Union[str, Sequence[str], None] = 'f7df96c3c0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('yield_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('yield_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('yield_amount_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('yield_payment_date', sa.Date(), nullable=True))
    op.add_column('transactions', sa.Column('yield_frequency', sa.String(), nullable=True))
    op.drop_column('transactions', 'cupom')
    op.drop_column('transactions', 'valor_mercado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('valor_mercado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('cupom', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'yield_frequency')
    op.drop_column('transactions', 'yield_payment_date')
    op.drop_column('transactions', 'yield_amount_type')
    op.drop_column('transactions', 'yield_amount')
    op.drop_column('transactions', 'yield_type')
    # ### end Alembic commands ###
